# Simple configuration for portfolio optimization
portfolio:
  # Risk parameters
  risk_free_rate: 0.02
  max_position_size: 0.05
  max_sector_concentration: 0.20

  # Trading parameters
  trading_days_per_year: 252
  default_period: "5y"

  # Performance thresholds
  min_sharpe_ratio: 1.0
  max_drawdown_threshold: 0.15

# Data settings
data:
  # Data validation
  min_data_points: 252
  max_missing_percentage: 0.05

  # Cache settings
  enable_caching: true
  cache_dir: "./cache"

# API settings (if needed)
api:
  host: "localhost"
  port: 8000
  debug: false