name: quant-portfolio-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pytest>=7.0.0
  - pyyaml>=6.0
  - pip:
    - yfinance>=0.2.0
    - cvxpy>=1.4.0
    - scikit-learn>=1.0.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0