version: 1
disable_existing_loggers: false
formatters:
  structured:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "event": "%(message)s"}'
    datefmt: '%Y-%m-%dT%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: structured
    filename: logs/risk/risk.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf-8
loggers:
  portfolio.risk:
    level: INFO
    handlers: [console, file]
    propagate: false
  portfolio.api.risk:
    level: INFO
    handlers: [console, file]
    propagate: false
root:
  level: WARNING
  handlers: [console]
