[trading]
symbols = [ "AAPL", "GOOGL",]
timeframe = "1d"
initial_capital = 10000.0
max_position_size = 0.1
commission = 0.001

[risk]
max_drawdown = 0.15
var_confidence = 0.95

[data]
provider = "yahoo_finance"
refresh_interval = 3600
cache_duration = 86400

[backtesting]
start_date = "2020-01-01"
end_date = "2023-12-31"
benchmark = "SPY"

[logging]
level = "DEBUG"
file = "logs/trading.log"
max_size = "10MB"
backup_count = 5

[risk.position_limits]
single_position = 0.05
sector_exposure = 0.2
